# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ac62a67c56cccdeaa7f72de9f992cf0f1ae2a4131920dad117e2b3472061a7537eb4b5b6386bfa58a42517df2ac3ad0511519d9d006c6536919ad91b2c7b955

test:
  secret_key_base: 5282102bb0f7a5863911e3ebdcb57e2e974898904a7e25581518cb20acb4e543c8b689819bfe12bb987f0473701826d435e59bf86d6fc784c2da174816c36292

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
